name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const assignees = ['X']; // Replace X with the GitHub username of the team member

            try {
              const response = await github.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                assignees: assignees,
              });
              console.log("Assignees added:", response.data);
            } catch (error) {
              console.error("Error adding assignees:", error);
              throw error; // This will mark the job as failed
            }
