name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue
        uses: octokit/request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          request: |
            POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
            {
              "assignees": ["X"] darya17b
            }
